import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ imageSrc }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>Image should changed after revalidation (1 sec)</div>
        <Image src={imageSrc} alt="changable image" width="64" height="64" />
      </main>
    </>
  );
}
let count = -1;
const images = ["/next.svg", "/thirteen.svg", "/vercel.svg"];

export const getStaticProps = () => {
  ++count;
  if (count > images.length - 1) {
    count = 0;
  }
  return {
    props: {
      imageSrc: images[count],
    },
    revalidate: 1,
  };
};
